Order/urls.py
from django.urls import path
from .views import verify_pay

app_name = 'order'

urlpatterns = [
    path('verify_pay/<str:ref>/', verify_pay, name='verify-pay')
]

store/urls.py
from django.urls import path
from .import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='store'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_categories'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('updateItem', views.updateItem, name='update_item'),


]

unboxed/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='account')),
    path('Order/', include('Order.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'store:store' %}">Umitrees<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
					
					<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
			<li class="text-white text-center" style="font-size:15px; font-family:cursive;">Items: {{order.count_cart}}</li>
			
		
		</ul> 

				</div>
			</div>
				
		</nav>
		<!-- End Header/Navigation -->

		

		

		<div class="untree_co-section before-footer-section">
            <div class="container">
              <div class="row mb-5">
                <form class="col-md-12" method="post">
                  <div class="site-blocks-table">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="product-thumbnail">Image</th>
                          <th class="product-name">Name</th>
                          <th class="product-price">Price</th>
                          <th class="product-quantity">Quantity</th>
                          <th class="product-total">Total</th>
                  
                        </tr>
                      </thead>
                      <tbody>
                        
                        {% for item in items %}
                        <tr>
                          <td class="product-thumbnail">
                            <img src="{{item.product.image.url}}" alt="Image" class="img-fluid">
                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">{{item.product.name}}</h2>
                          </td>
                          <td>NGN {{item.product.price}}</td>
                          <td>
                            <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button data-product={{item.product.id}} data-action='remove' class="btn btn-outline-black decrease update-cart" type="button">&minus;</button>
                              </div>
                              <input type="text" class="form-control text-center quantity-amount" value="{{item.quantity}}" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                              <div class="input-group-append">
                                <button data-product={{item.product.id}} data-action='add' class="btn btn-outline-black increase update-cart" type="button">&plus;</button>
                              </div>
                            </div>
                          </td>
                          <td>NGN {{item.get_total}}</td>
                          <td><a href="#" class="btn btn-black btn-sm">X</a></td>
                        </tr>
                      {% empty %}
                      <h3 class="text-black h4 ">Cart Is Currently Empty </h3>
                        {% endfor %}
        
                        
                      </tbody>
                    </table>
                  </div>
                </form>
              </div>
        
              <div class="row">
                <div class="col-md-6">
                  <div class="row mb-5">
           
                    <div class="col-md-6">
                      <a href="{% url 'store:store' %}" class="btn btn-outline-black btn-sm btn-block">Continue Shopping</a>
                    </div>
                  </div>
                  <!-- <div class="row">
                    <div class="col-md-12">
                      <label class="text-black h4" for="coupon">Coupon</label>
                      <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                      <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                      <button class="btn btn-black">Apply Coupon</button>
                    </div>
                  </div> -->
                </div>
                <div class="col-md-6 pl-5">
                  <div class="row justify-content-end">
                    <div class="col-md-7">
                      <div class="row">
                        <div class="col-md-12 text-right border-bottom mb-5">
                          <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                        </div>
                      </div>
                      <!-- <div class="row mb-3">
                        <div class="col-md-6">
                          <span class="text-black">Subtotal</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">$230.00</strong>
                        </div>
                      </div> -->
                      <div class="row mb-5">
                        <div class="col-md-6">
                          <span class="text-black">Total</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">NGN {{order.get_cart_total}}</strong>
                        </div>
                      </div>
        
                      <div class="row">
                        <div class="col-md-12">
                          <a class="btn btn-black btn-lg py-3 btn-block" href="{% url 'store:checkout' %}">Proceed To Checkout</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
		
{% endblock %} 
	

templates/cart/cart_icon.html
{% load static %}

templates/cart/cart_payment.html
{% extends "account/lognav.html" %}
   

{% block content %}
    
          <script src="https://js.paystack.co/v1/inline.js"></script>

                <div class="flex flex-col space-y-10 mt-3">
              <h4 class="text-center pt-5 font-extrabold text-2xl">Are you sure you want to proceed?</h4>
                <div class="flex justify-between">
                    <h6 class="text-xl text-base font-extrabold">Total</h6>
                    <p class="text-xl text-base">&#8358; {{order.get_cart_total}}</p>
                </div>
                  <button onclick="payWithPaystack()"  class="bg-gray-100 p-3 rounded-lg hover:opacity-70 font-base text-xl">Pay</button>
                       <a href="{% url 'store:cart'%}" class="p-3 bg-gray-200 rounded-lg hover:opacity-70 font-base text-xl text-center">Cancel</a>
                </div>


  
     <script>

function payWithPaystack() {
  var handler = PaystackPop.setup({
    key: '{{paystack_key}}', // Replace with your public key
    email: "{{order.getCustomerEmail}}",
    amount:  "{{order.get_cart_total}}" * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
    currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
    ref: '{{order.ref}}', // Replace with a reference you generated
    callback: function(response) {
      //this happens after the payment is completed successfully
      var reference = response.reference;
      alert('Payment complete! Reference: ' + reference);
      window.location.href = "{% url 'order:verify-pay' order.ref %}"
      url = "{% url 'order:verify-pay' order.ref %}"
      console.log(url)
      
    },
    onClose: function() {
      alert('Transaction was not completed, window closed.');
    },
  });
  handler.openIframe();
}
</script>
  
{% endblock content %}

templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"rel="stylesheet"/>
		<!-- Start Header/Navigation -->

		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'store:store' %}">Umitrees<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

			
			</div>
				
		</nav>
		<!-- End Header/Navigation -->


		<div class="untree_co-section">
			<form  method="post">
				{% csrf_token %}
		    <div class="container">
		      <div class="row mb-5">
		        <div class="col-md-12">
		       
		        </div>
		      </div>
		      <div class="row">
		        <div class="col-md-6 mb-5 mb-md-0">
		          <h2 class="h3 mb-3 text-black">Billing Details</h2>
		          <div class="p-3 p-lg-5 border bg-white">
		            
		            <div class="form-group row">
		              <div class="col-md-6">
		                <label for="c_fname" class="text-black">First Name <span class="text-danger">*</span></label>
		                {{form.first_name}}
		              </div>
		              <div class="col-md-6">
		                <label for="c_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
		                {{form.last_name}}
		              </div>
		            </div>

		            

		            <div class="form-group row">
		              <div class="col-md-12">
		                <label for="c_address" class="text-black">Address <span class="text-danger">*</span></label>
		                {{form.address}}
		              </div>
		            </div>

		           
		            <div class="form-group row">
		              <div class="col-md-6">
		                <label for="c_state_country" class="text-black">State<span class="text-danger">*</span></label>
		                {{form.state}}
		              </div>
		              <div class="col-md-6">
		                <label for="c_postal_zip" class="text-black">City<span class="text-danger">*</span></label>
		                {{form.city}}
		              </div>
		            </div>

		            <div class="form-group row mb-5">
		              <!-- <div class="col-md-6">
		                <label for="c_email_address" class="text-black">Email Address <span class="text-danger">*</span></label>
		                {{form.mobile}}
		              </div> -->
		              <div class="col-md-6">
		                <label for="c_phone" class="text-black">Phone <span class="text-danger">*</span></label>
		                {{form.mobile}}
		              </div>
		            </div>

		          </div>
		        </div>
				
		        <div class="col-md-6">

		          <div class="row mb-5">
		            <div class="col-md-12">
		              <h2 class="h3 mb-3 text-black">Coupon Code</h2>
		              <div class="p-3 p-lg-5 border bg-white">

		                <label for="c_code" class="text-black mb-3">Enter your coupon code if you have one</label>
		                <div class="input-group w-75 couponcode-wrap">
		                  <input type="text" class="form-control me-2" id="c_code" placeholder="Coupon Code" aria-label="Coupon Code" aria-describedby="button-addon2">
		                  <div class="input-group-append">
		                    <button class="btn btn-black btn-sm" type="button" id="button-addon2">Apply</button>
		                  </div>
		                </div>

		              </div>
		            </div>
		          </div>

		          <div class="row mb-5">
		            <div class="col-md-12">
		              <h2 class="h3 mb-3 text-black">Your Order</h2>
		              <div class="p-3 p-lg-5 border bg-white">
		                <table class="table site-block-order-table mb-5">
		                  <thead>
		                    <th>Product</th>
		                    <th>Total</th>
		                  </thead>
		                  <tbody>
		               {% for item in items %}
		                    <tr>
		                      <td>{{item.product.name}} <strong class="mx-2">x</strong>{{item.quantity}}</td>
		                      <td>NGN {{item.get_total}}</td>
		                    </tr>
		                    {% endfor %}
		                    
		                    <tr>
		                      <td class="text-black font-weight-bold"><strong>Order Total</strong></td>
		                      <td class="text-black font-weight-bold"><strong>NGN {{order.get_cart_total}}</strong></td>
		                    </tr>
		                  </tbody>
		                </table>

		                <div class="form-group">
		                  <button type="submit" class="btn btn-black btn-lg py-3 btn-block">Place Order</button>
		                </div>
						
		               
		              </div>
		            </div>
		          </div>

		        </div>
		      </div>
		      </form>
		    </div>
		  </div>

		  <div class="bg-black opacity-90 w-full h-full p-10  absolute top-0" style="display: none;" id="modal">
	
			<div class="modal-content w-2/5 p-10  absolute bg-white top-20 left-1/3 ">
				<span class="text-end" id="close-modal">X</span>
				<h2 class="text-center text-4xl font-extrabold">Checkout Payment</h2>
				<div class="flex space-x-20 mt-5 m-0 m-auto">
				<button class="p-3 bg-blue-300">Back</button>
				<button class="p-3 bg-green-200 ">Proceed to Pay</button>
				</div>
				
			</div>
				
		  </div>


<script>
	const openModalBtn = document.getElementById('open-modal');
		const closeModalBtn = document.getElementById('close-modal');
		const modal = document.getElementById('modal');

		openModalBtn.addEventListener('click', () => {
			modal.style.display = 'block';
		});

		closeModalBtn.addEventListener('click', () => {
			modal.style.display = 'none';
		});

		window.addEventListener('click', (event) => {
			if (event.target === modal) {
				modal.style.display = 'none';
			}
		});





</script> 

{% endblock content %}

templates/cart/checkout_clown.html
<style>
	.modal {
  display: none;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: rgba(0, 0, 0, 0.4);
}

.modal-content {
  background-color: #fefefe;
  margin: 15% auto;
  padding: 20px;
  border-radius: 15px;
  width: 30%;
}

.close {
  color: #aaa;
  padding-left: 11em;
  font-size: 28px;
  font-weight: bold;
  cursor: pointer;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

</style>

<h2>Check Out</h2>

<h5>Billing Details</h5>

<div>
    <form action="." method="post">
        {{form.as_p}}
        <button id="open-modal" type="button">Place Order</button>
    </form>
</div>




<div id="modal" class="modal">
  <div class="modal-content">
    <span id="close-modal" class="close">&times;</span>
    <h4 style="padding-left:20px;">Total: NGN {{order.get_cart_total}}</h4>
	

	<hr>
	<ul style="padding-left:20px;">
	<a href="" class="btn btn-black">Back</a>
     <script src="https://js.paystack.co/v1/inline.js"></script>
	<button class="btn btn-primary" type="submit" onclick="payWithPayStack()">Proceed to pay</button>
	</ul>
  </div>
  
  
</div>

<script>
	const openModalBtn = document.getElementById('open-modal');
		const closeModalBtn = document.getElementById('close-modal');
		const modal = document.getElementById('modal');

		openModalBtn.addEventListener('click', () => {
			modal.style.display = 'block';
		});

		closeModalBtn.addEventListener('click', () => {
			modal.style.display = 'none';
		});

		window.addEventListener('click', (event) => {
			if (event.target === modal) {
				modal.style.display = 'none';
			}
		});



        function payWithPayStack(){
            let currency = "NGN";
            let plan = "";
            let ref = "{{order.ref}}";
            let obj = {
                key: "{{paystack_key}}",
                email: "{{order.getCustomerEmail}}",
                amount: "{{order.get_cart_total}}",
                ref:ref,
                callback: function(response){
                    window.location.href = "{% url 'store:verify-payment' order.ref %}"
                }
            }
            
            if (Boolean(currency)){
                obj.currency = currency.toUpperCase()
            }

            if (Boolean(plan)){
                obj.plan = plan;
            }
            var handler = PaystackPop.setup(obj);
            handler.openIframe();
        }
</script>

templates/cart/thankyou.html
{% extends "base.html" %}
{% load static %}


{% block content %}
	

	
		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'store:store' %}">Umitrees<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				
			</div>
				
		</nav>
		<!-- End Header/Navigation -->

		

		

		<div class="untree_co-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center pt-5">
          <span class="display-3 thankyou-icon text-primary">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
              <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
            </svg>
          </span>
          <h2 class="display-3 text-black">Thank you!</h2>
          <p class="lead mb-5">You order was successfuly completed.</p>
          <p><a href="{% url 'store:store' %}" class="btn btn-sm btn-outline-black">Back to shop</a></p>
        </div>
      </div>
    </div>
  </div>

		
{% endblock content %}