Order/urls.py
from django.urls import path
from .views import verify_pay

app_name = 'order'

urlpatterns = [
    path('verify_pay/<str:ref>/', verify_pay, name='verify-pay')
]

accounts/urls.py
from django.urls import path
from .views import login_page, logoutUser, signUp

app_name = 'account'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('logout/', logoutUser, name='log-out'),
    path('signup/', signUp, name='sign-up'),
]

store/urls.py
from django.urls import path
from .import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='store'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_categories'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('updateItem', views.updateItem, name='update_item'),


]

unboxed/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='account')),
    path('Order/', include('Order.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.urls import reverse



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("store:product_list_by_categories", args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='media', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.id, self.slug])
    

store/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product
from Order.models import Order, OrderItem
import json
from django.core.exceptions import MultipleObjectsReturned
from Order.forms import ShippingAddressForm
from django.contrib import messages
from django.conf import settings
import time

def product_list(request, category_slug=None):
    user = request.user
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        print('category slug: ',category_slug)
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
       
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, verified=False)
        items = order.order_items.all()
        cartItems = order.count_cart
        
    else:
        items = []
        order = {'get_cart_total':0, 'count_cart':0}
        cartItems = order['count_cart']

    context ={
        'category':category,
        'categories':categories,
        'products': products,
        'cartItems': cartItems,
        'user': user
        
        
    }

    return render(request, 'store/shop.html', context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, verified=False)
        items = order.order_items.all()
        mail = order.getCustomerEmail
    
        
    else:
        items = []
        order = {'get_cart_total':0, 'count_cart':0}
        
 
    context = {'items':items, 'order':order}
    return render(request, 'cart/cart.html', context)


def checkout(request):
    
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, verified=False)
        items = order.order_items.all()
        
        
    else:
        items = []
        order = {'get_cart_total':0, 'count_cart':0}

    if request.method == 'POST':
        form = ShippingAddressForm(request.POST)
        if form.is_valid():
            shipping_address = form.save(commit=False)
            shipping_address.customer = customer
            shipping_address.order = order
            shipping_address.save()
            print(shipping_address)
            return render(request, 'cart/cart_payment.html', {'order':order, 'paystack_key':settings.PAYSTACK_PUBLIC_KEY})
    else:
        form = ShippingAddressForm()
    context = {'items':items, 'order':order, 'form':form}
    return render(request, 'cart/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('ID:', productId, 'Action:', action)

    customer = request.user
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, verified=False)
    # order = Order.objects.create(customer=customer, verified=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    # orderItem = OrderItem.objects.create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = orderItem.quantity + 1
    elif action == 'remove':
        orderItem.quantity = orderItem.quantity - 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False) 

templates/store/shop.html
{% extends 'base.html' %}		
{% load static %}
{% block title %}
{% if category %} {{category.name}}{% else %}Products {% endif %}
{% endblock title %}
{% block content %}

<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'store:store' %}">Umitrees<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
						
						<!-- <li><a class="nav-link" href="{% url 'store:store' %}">All</a></li> -->
						<!-- {% for items  in categories  %}
						<li><a class="nav-link" href="{{items.get_absolute_url}}">{{items.name}}</a></li>
						{% endfor %} -->
					</ul>

			<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">				
				{% if user.is_authenticated %}
					<li><a class="nav-link" href="{% url 'account:log-out' %}"><img src="{% static 'images/user.svg' %}"></a></li>
					{% else %}
					<li><a class="nav-link" href="{% url 'account:login' %}"><img src="{% static 'images/user.svg' %}"></a></li>
				{% endif %}

<!--<li><a class="nav-link" href="{% url 'account:login' %}"><img src="{% static 'images/user.svg' %}"></a></li> -->

			<li><a class="nav-link" href="{% url 'store:cart' %}"><img src="{% static 'images/cart.svg' %}"></a></li>
			<span class="text-white text-center bg-secondary" style="height: 25px; width:15px; border-radius:100px; ">{{cartItems}}</span>
		
		</ul> 
				

				</div>
			</div>
				 
		</nav>
		
	

		<div class="untree_co-section product-section before-footer-section">
		    <div class="container">
		      	<div class="row">

					{% for product in products  %}
		      		<!-- Start Column 1 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5">
						<span class="product-item">
							<img src="{{product.image.url}}" class="img-fluid product-thumbnail">
							<h3 class="product-title">{{product.name}}</h3>
							<strong class="product-price">NGN {{product.price}}</strong>
							
							{% if user.is_authenticated %}
								<span data-product="{{product.id}}"data-action="add" class="icon-cross add-btn update-cart">
								<img src="{%static 'images/cross.svg' %}" class="img-fluid">
							</span>
							{% else %}
							<span onclick="alert('You need to login in first!')" data-product="{{product.id}} "data-action="add" class="icon-cross add-btn update-cart">
								<img src="{%static 'images/cross.svg' %}" class="img-fluid">
							</span>
							{% endif %}
								
							
							
						</span>
					</div> 
					<!-- End Column 1 -->
					{% endfor %}

		      	</div>
		    </div>
		</div>

{% endblock content %}

		